apiVersion:  apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    tier: database
    project: roboshop
    code: mongo-db-rs-dev
spec:
  replicas: 1
  matchLabes:
    selectLabels:
      code: mongo-db-rs-dev
  template:
    metadata:
      labels:
        component: mongodb
        tier: database
        project: roboshop
        code: mongo-db-rs-dev
    spec:
      containers:
      - name: mongodb-pod
        image: "{{ .Values.deployment.image_url}}:{{ .Values.deployment.image_version }}"
        ports:
        - containerPort: 27017
        imagePullPolicy: Always
